# This is a basic workflow to help you get started with Actions

name: Terraform plan, fmt, validate.

pr:
  branches:
    include:
      - 'dev'
      - 'main'

pool:
  vmImage: 'ubuntu-latest'

steps:

- checkout: self

- task: TerraformInstaller@0
  inputs:
    terraformVersion: '0.14.6'
  displayName: 'Install Terraform'

- script: |
    terraform fmt -check
  displayName: 'Terraform fmt check'
  workingDirectory: environment/
  enabled: 'true'

- task: TerraformCLI@0
  displayName: 'Terraform init'
  inputs:
    command: 'init'
    commandOptions: '-input=false'
    backendType: 'azurerm'
    backendServiceArm: 'Azure subscription 1(ea03101c-5276-4bbf-8ba6-aa35de47234f)'
    backendAzureRmResourceGroupName: 'home'
    backendAzureRmStorageAccountName: 'tfbackendsahome'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'prod.terraform.state'
    allowTelemetryCollection: false
    workingDirectory: environment/

- script: |
    terraform validate
  displayName: 'Terraform validate'
  workingDirectory: environment/
  enabled: 'true'

- task: TerraformCLI@0
  displayName: 'Terraform plan'
  inputs:
    command: 'plan'
    commandOptions: '-lock=false -input=false'
    environmentServiceName: 'Azure subscription 1(ea03101c-5276-4bbf-8ba6-aa35de47234f)'
    allowTelemetryCollection: false
    workingDirectory: environment/