# This is a basic workflow to help you get started with Actions

name: Terraform plan, fmt, validate.

pr:
  branches:
    include:
      - 'dev'
      - 'main'

pool:
  vmImage: 'ubuntu-latest'

steps:

- checkout: self

- task: TerraformInstaller@0
  inputs:
    terraformVersion: '0.14.6'
  displayName: 'Install Terraform'

- script: |
    terraform fmt -check
  displayName: 'Terraform fmt check'
  workingDirectory: environment/
  enabled: 'true'

- task: TerraformCLI@0
  inputs:
    command: 'init'
    commandOptions: '-input=false'
    backendType: 'azurerm'
    backendServiceArm: 'Databricks_CS(6369c148-f8a9-4fb5-8a9d-ac1b2c8e756e)'
    backendAzureRmResourceGroupName: 'home'
    backendAzureRmStorageAccountName: 'tfbackendsahome'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'prod.terraform.state'
    allowTelemetryCollection: false