# This is a basic workflow to help you get started with Actions

name: Validate Databricks Terraform pipeline

variables:
  - group: 'TerraformProdDeploy'

pr:
  branches:
    include:
      - 'dev'
      - 'main'

pool:
  vmImage: 'ubuntu-latest'

steps:

- checkout: self

- task: TerraformInstaller@0
  inputs:
    terraformVersion: '1.0.11'
  displayName: 'Install Terraform'

- script: |
    echo "[DEFAULT]" >> ~/.databrickscfg
    echo "host = $DATABRICKS_HOST" >> ~/.databrickscfg
    echo "token = $DATABRICKS_TOKEN" >> ~/.databrickscfg
  env:
    DATABRICKS_HOST: $(DATABRICKS_HOST)
    DATABRICKS_TOKEN: $(DATABRICKS_TOKEN)
  displayName: 'Set up Databricks cli profile for Terraform provider'

- script: |
    terraform fmt -check
  displayName: 'Terraform fmt check'
  workingDirectory: environment/
  enabled: 'true'

- task: TerraformCLI@0
  displayName: 'Terraform init'
  inputs:
    command: 'init'
    commandOptions: '-input=false'
    backendType: 'azurerm'
    backendServiceArm: $(SERVICE_CONNECTION_NAME)
    backendAzureRmResourceGroupName: $(BACKEND_RG_NAME)
    backendAzureRmStorageAccountName: $(BACKEND_SA_NAME)
    backendAzureRmContainerName: $(BACKEND_CONTAINER_NAME)
    backendAzureRmKey: $(BACKEND_KEY)
    allowTelemetryCollection: false
    workingDirectory: environment/

- script: |
    terraform validate
  displayName: 'Terraform validate'
  workingDirectory: environment/
  enabled: 'true'

- task: TerraformCLI@0
  displayName: 'Terraform plan'
  inputs:
    command: 'plan'
    commandOptions: '-lock=false -input=false'
    environmentServiceName: $(SERVICE_CONNECTION_NAME)
    allowTelemetryCollection: false
    workingDirectory: environment/
