# This is a basic Azure DevOps pipeline to validate Terraform

name: Validate Databricks Terraform pipeline

variables:
  - group: 'TerraformProdDeploy'

# We disable builds for any commits as everything should go through pull requests
trigger: none

pr:
  branches:
    include:
    - main
  paths:
    exclude:
    - README.md
    - images
    
pool:
  vmImage: 'ubuntu-latest'

steps:

- checkout: self

- task: TerraformInstaller@0
  inputs:
    terraformVersion: '1.0.11'
  displayName: 'Install Terraform'

- script: |
    echo "[DEFAULT]" >> ~/.databrickscfg
    echo "host = $DATABRICKS_HOST" >> ~/.databrickscfg
    echo "token = $DATABRICKS_TOKEN" >> ~/.databrickscfg
  env:
    DATABRICKS_HOST: $(DATABRICKS_HOST)
    DATABRICKS_TOKEN: $(DATABRICKS_TOKEN)
  displayName: 'Set up Databricks CLI profile for Terraform provider'

- script: |
    terraform fmt -check
  displayName: 'Terraform fmt check'
  workingDirectory: environment/
  enabled: 'true'

- task: TerraformCLI@0
  displayName: 'Terraform init'
  inputs:
    command: 'init'
    commandOptions: '-input=false -no-color'
    backendType: 'azurerm'
    backendServiceArm: $(SERVICE_CONNECTION_NAME)
    backendAzureRmResourceGroupName: $(BACKEND_RG_NAME)
    backendAzureRmStorageAccountName: $(BACKEND_SA_NAME)
    backendAzureRmContainerName: $(BACKEND_CONTAINER_NAME)
    backendAzureRmKey: $(BACKEND_KEY)
    allowTelemetryCollection: false
    workingDirectory: environment/

# - script: |
#     terraform validate -no-color
#   displayName: 'Terraform validate'
#   workingDirectory: environment/
#   enabled: 'true'

- task: TerraformCLI@0
  displayName: 'Terraform validate'
  inputs:
    command: 'validate'
    commandOptions: '-no-color'
    environmentServiceName: $(SERVICE_CONNECTION_NAME)
    allowTelemetryCollection: false
    workingDirectory: environment/

- task: TerraformCLI@0
  displayName: 'Terraform plan'
  inputs:
    command: 'plan'
    commandOptions: '-lock=false -input=false -no-color'
    environmentServiceName: $(SERVICE_CONNECTION_NAME)
    allowTelemetryCollection: false
    workingDirectory: environment/
